# Generated by Django 4.2.16 on 2025-11-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_space_member_space_session_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='extra_member_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False)), fields=('space', 'phone'), name='unique_phone_per_space'),
        ),
    ]
